telegram:
  mode: polling
  unresolved-filter:
    enabled: false

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tbot
    username:
    password:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: true

parsers: html=http://localhost:8888/rss?url=%s